---
name: lints
permissions:
  contents: read

on:
  push:
    branches:
      - nt-github-actions-ci
    paths-ignore:
      - "**.md"

  pull_request:
    branches:
      - nt-github-actions-ci
    paths-ignore:
      - "**.md"

jobs:
  lints:
    name: run CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #tag v2.4.0
        with:
          persist-credentials: false

      - uses: marc-casperlabs/casper-ci@v1

      - name: fmt
        run: make check-format

      - name: clippy
        run: make lint

      - name: doc
        run: make doc

      - name: audit
        run: make audit
